apiVersion: v1
kind: Pod
metadata:
  name: config-loader
spec:
  restartPolicy: Never
  containers:
    - image: bbvainnotech/k8s-config-loader:latest
      imagePullPolicy: Always
      name: config-loader


