apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nuage-vsc
  name: nuage-vsc
  namespace: default
spec:
  selector:
    app: nuage-vsc
  template:
    metadata:
      labels:
        app: nuage-vsc
    spec:
      containers:
      - image: vsc:v0.1-nuage
        imagePullPolicy: Always
        securityContext:
          privileged: true
        name: nuage-vsc
        tty: true
        stdin: true
        ports:
        - containerPort: 6633
          protocol: TCP
        - containerPort: 7406
          protocol: TCP
        - containerPort: 179
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/pts
          name: dev-pts
      volumes:
      - name: dev-pts
        hostPath:
          path: /dev/pts

