apiVersion: v1
kind: Service
metadata:
  name: vsc
  labels:
    app: vsc
spec:
  ports:
    - port: 6633
      name: openflow
    - port: 7406
      name: json-rpc
    - port: 179
      name: bgp
  selector:
    app: vsc