apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: cinder
  name: cinder
  namespace: default
spec:
  selector:
    app: cinder
  template:
    metadata:
      labels:
        app: cinder
    spec:
      containers:
      - image: cinder:v0.3
        imagePullPolicy: Always
        name: cinder
        ports:
        - containerPort: 8776
          protocol: TCP
        volumeMounts:     
          - name: www      
            mountPath: "/var/tmp/"
      volumes:
        - name: www
          nfs:
            server: 172.16.26.11
            path: "/vol_NFS_CLOUD_EP_cinder1"
