apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: cinder
  name: cinder
  namespace: default
spec:
  selector:
    app: cinder
  template:
    metadata:
      labels:
        app: cinder
    spec:
      hostNetwork: true
      containers:
      - image: cinder:v0.3
        imagePullPolicy: Always
        name: cinder
        ports:
        - containerPort: 8776
          protocol: TCP
