apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: cinder
  name: cinder
  namespace: default
spec:
  selector:
    app: cinder
  template:
    metadata:
      labels:
        app: cinder
    spec:
      containers:
      - image: bbvainnotech/k8s-cinder:latest
        imagePullPolicy: Always
        name: cinder
        securityContext:
          privileged: true
        ports:
        - containerPort: 8776
          protocol: TCP
