#### heat replication controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: heat
  name: heat-nuage
  namespace: default
spec:
  selector:
    app: heat
  template:
    metadata:
      labels:
        app: heat
    spec:
      containers:
      - image: k8s-heat:latest-nuage
        imagePullPolicy: Always
        name: heat-nuage
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8004
          protocol: TCP
        - containerPort: 8003
          protocol: TCP
