apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nova-compute-neutr0n
  name: nova-compute-neutr0n
  namespace: default
spec:
  selector:
    app: nova-compute-neutr0n
  template:
    metadata:
      labels:
        app: nova-compute-neutr0n
    spec:
      containers:
      - image: bbvainnotech/libvirtd:latest
        imagePullPolicy: Always
        name: nova-compute-libvirt
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: "modules"
        - mountPath: /var/lib/libvirt
          name: "libvirt"
        - mountPath: /var/lib/nova/instances
          name: "nova"
      - image: bbvainnotech/k8s-nova-compute-neutron:latest
        imagePullPolicy: Always
        name: nova-compute-neutr0n
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/libvirt
          name: "libvirt"
        - mountPath: /var/lib/nova/instances
          name: "nova"
        - mountPath: /lib/modules
          name: "modules"
      volumes:
      - hostPath:
          path: /lib/modules
        name: modules
      - hostPath:
          path: /var/lib/libvirt
        name: libvirt
      - hostPath:
          path: /var/lib/nova/instances
        name: nova