apiVersion: v1
kind: ReplicationController
metadata:
  name: rmq-node-1
spec:
  replicas: 1
  selector:
    name: rmq-node-1
  template:
    metadata:
      labels:
        name: rmq-node-1
        type: rmq-node
    spec:
      containers:
        - name: rmq
          image: bbvainnotech/k8s-rabbitmq-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 15672
              protocol : TCP
              name : admin-port
            - containerPort: 5672
              protocol : TCP
              name : default
            - containerPort: 4369
              protocol : TCP
              name : epmd-port
            - containerPort: 25672
              protocol : TCP
              name : dist-port
